/**
 * Generates a HTML report form a given set of JSON report files
 *
 * @module given-html-report
 */

'use strict';

var fs = require('fs-extra');

var path = require('path');
var glob = require('glob');


/**
 *
 * @param {[string]} inputFiles list of input files, which contain the JSON reports generated by GivenJS or JGiven
 * @param {string} targetDir the directory where to generate the HTML report to
 */
module.exports = function generateHtmlReport(inputFiles, targetDir) {
  console.log("Generating GivenJS report to directory " + targetDir + " ...");

  var jsonInputs = [];


  console.log("Creating " + targetDir);
  fs.mkdirpSync(targetDir);

  console.log("Copy static data to " + targetDir);

  glob(__dirname + "/../app", function (err, files) {
    files.forEach(function (file) {
      fs.copySync(file, targetDir);
    });
  });

  program.args.forEach(function (arg) {
    glob(arg, function (err, files) {
      files.forEach(function (file) {
        console.log("Reading " + file);
        jsonInputs.push(JSON.parse(fs.readFileSync(file, "utf8")));
      });
    });
  });
};

